stages:
    - test

test:
    image: rootproject/root-ubuntu16
    stage: test
    script:
    - echo "Running tests"
    - export PYTHONPATH="$PYTHONPATH:$PWD"
    - python -V
    - python -m unittest discover test
